spring:
  application:
    name: atmbackend-ms
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/atmBackend
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/atmbackend?authSource=admin&authMechanism=SCRAM-SHA-1
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mainUsername:sevilsariyeva00@gmail.com}
    password: "..."
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
